const {
    decNumRule,
    decTimestamp,
    decTsMs,
    decTsMcs,
    decTsNs,
    decIpv4Rule,
    decIpv6Rule,
    decMacRule,
    decStringRule,
    decAsciiStringRule,
} = require('../nf9/fieldRules');


const cisco = {
    4235: { name: 'counter_bytes_rate', compileRule: decNumRule },
    4236: { name: 'application_media_bytes_counter', compileRule: decNumRule },
    4238: { name: 'application_media_bytes_rate', compileRule: decNumRule },
    4239: { name: 'application_media_packets_counter', compileRule: decNumRule },
    4241: { name: 'application_media_packets_rate', compileRule: decNumRule },
    4246: { name: 'transport_packets_expected_counter', compileRule: decNumRule },
    4251: { name: 'transport_packets_lost_counter', compileRule: decNumRule },
    4253: { name: 'transport_packets_lost_rate', compileRule: decNumRule },
    4254: { name: 'transport_rtp_ssrc', compileRule: decNumRule },
    4255: { name: 'transport_rtp_jitter_mean', compileRule: decNumRule },
    4256: { name: 'transport_rtp_jitter_minimum', compileRule: decNumRule },
    4257: { name: 'transport_rtp_jitter_maximum', compileRule: decNumRule },
    4273: { name: 'transport_rtp_payload_type', compileRule: decNumRule },
    4325: { name: 'transport_rtp_jitter_mean_sum', compileRule: decNumRule },
    8337: { name: 'connection_server_counter_bytes_network', compileRule: decNumRule },
    8338: { name: 'connection_client_counter_bytes_network', compileRule: decNumRule },
    9254: { name: 'connection_delay_network_long_lived_to_', compileRule: decNumRule },
    9255: { name: 'connection_delay_network_long_lived_to_', compileRule: decNumRule },
    9256: { name: 'connection_delay_network_long_lived_cli', compileRule: decNumRule },
    9257: { name: 'connection_delay_network_client_to_serv', compileRule: decNumRule },
    9258: { name: 'connection_delay_network_to_server_num_', compileRule: decNumRule },
    9259: { name: 'connection_delay_network_to_client_num_', compileRule: decNumRule },
    9267: { name: 'connection_client_counter_bytes_retrans', compileRule: decNumRule },
    9268: { name: 'connection_client_counter_packets_retra', compileRule: decNumRule },
    9269: { name: 'connection_server_counter_bytes_retrans', compileRule: decNumRule },
    9270: { name: 'connection_server_counter_packets_retra', compileRule: decNumRule },
    9272: { name: 'connection_transaction_counter_complete', compileRule: decNumRule },
    9273: { name: 'connection_transaction_duration_sum', compileRule: decNumRule },
    9274: { name: 'connection_transaction_duration_max', compileRule: decNumRule },
    9275: { name: 'connection_transaction_duration_min', compileRule: decNumRule },
    9292: { name: 'connection_server_counter_responses', compileRule: decNumRule },
    9300: { name: 'connection_delay_response_to_server_his', compileRule: decNumRule },
    9303: { name: 'connection_delay_response_to_server_sum', compileRule: decNumRule },
    9306: { name: 'connection_delay_application_sum', compileRule: decNumRule },
    9309: { name: 'connection_delay_response_client_to_ser', compileRule: decNumRule },
    12230: { name: 'application_family_name', compileRule: decStringRule },
    12231: { name: 'application_set_name', compileRule: decStringRule },
    12232: { name: 'application_category_name', compileRule: decStringRule },
    12233: { name: 'application_sub_category_name', compileRule: decStringRule },
    12234: { name: 'application_group_name', compileRule: decStringRule },
    12236: { name: 'connection_client_ipv4_address', compileRule: decIpv4Rule },
    12237: { name: 'connection_server_ipv4_address', compileRule: decIpv4Rule },
    12241: { name: 'connection_server_transport_port', compileRule: decNumRule },
    12243: { name: 'application_traffic_class', compileRule: decNumRule },
    12244: { name: 'application_business_relevance', compileRule: decNumRule },
    12432: { name: 'ingressoverlaysessionid', compileRule: decNumRule },
    12433: { name: 'egressoverlaysessionid', compileRule: decNumRule },
    12434: { name: 'routing_vrf_service', compileRule: decNumRule },
    12435: { name: 'tloc_table_overlay_session_id', compileRule: decNumRule },
    12436: { name: 'tloc_local_system_ip_address', compileRule: decIpv4Rule },
    12437: { name: 'tloc_local_color', compileRule: decNumRule },
    12438: { name: 'tloc_remote_system_ip_address', compileRule: decIpv4Rule },
    12439: { name: 'tloc_remote_color', compileRule: decNumRule },
    12440: { name: 'tloc_tunnel_protocol', compileRule: decNumRule },
    12441: { name: 'connection_id_long', compileRule: decNumRule },
    12442: { name: 'drop_cause_id', compileRule: decNumRule },
    12443: { name: 'counter_bytes_sdwan_dropped_long', compileRule: decNumRule },
    12444: { name: 'sdwan_sla_not_met', compileRule: decNumRule },
    12445: { name: 'sdwan_preferred_color_not_met', compileRule: decNumRule },
    12446: { name: 'sdwan_qos_queue_id', compileRule: decNumRule },
    42329: { name: 'counter_packets_sdwan_dropped_long', compileRule: decNumRule },
};

module.exports = {
    enterpriseTypes: {
        9: cisco,
    },
};
